### ISSUE TITLE
The issue? Everything.

### ISSUE THREAD

**Issue by Zilacon** [sfinnqs/colored-player-names#1]
This plugin ignores its own permissions. Permissions are set for individual colors for certain ranks and it ignores it.

The plugin overwrites and eliminates any competition period. We use a bungee chat plugin that allows others to communicate through other servers, this disables that and overwrites it completely.

This plugin also disables and overwrites all prefix, suffix, etc set by permission plugins such as GroupManager.

There is no reload command.

There is no way to disable specific features of this plugin.

There is zero compatibility with others. For example, Essentials will disable certain parts of the plugin if another plugin on the server is doing a similar thing.

The only positive thing i have to say about this plugin is it actually works. I have tried over 10 different nameplate changers including TagAPI, NameTags, ColoredNamePlates, etc and none of them have worked on 1.6.4.

The only thing i want from this plugin is permission based coloring for the players nameplates. However in trying to use it for that its basically ruined everything else that is setup on my network for chatting and ranks.

**Comment by fvoichick** [comment]
Hi Zilacon, I'm sorry that I haven't worked on this plugin for years. I just returned to it and completely rewrote it, and I think I've addressed all of these problems.

* I was originally doing static colors through the permissions system. I think that this was confusing and problematic, so static colors are now done in the configuration.
* I have added the ability to disable the scoreboard system.
* This plugin does overwrite display names with colored versions, meaning that custom prefixes will get overwritten. I have added the ability (through permissions) to exempt certain players from name coloring, in case you want to retain prefixes.
* I have added a reload command (`/cpn reload`).
I know you've probably forgotten about this plugin and don't care at this point, but I'm closing this issue and hopefully others can benefit from these fixes. Thanks for pointing out these issues.
